// src/components/Window.tsx
import WindowBorder from './WindowBorder.tsx'
import WindowTitlebar from './WindowTitlebar.tsx'

function Window() {
    const [light, medium, dark] = ['', '', '']
    console.log(light, medium, dark)

    return (
        <div className="window">
            <WindowBorder />
            <WindowTitlebar />
            <div className="window__content"></div>
        </div>
    )
}

export default Window

// src/lib/components/Window.svelte
<script lang="ts">
    import WindowBorder from "$lib/components/WindowBorder.svelte"
    import WindowTitlebar from "$lib/components/WindowTitlebar.svelte"

    export let engraved: Boolean = false
</script>

<div
    class="window"
    class:window--engraved={engraved}
>
    <WindowBorder />
    <WindowTitlebar />
    <div class="window__content">

    </div>
</div>
